### PR TITLE
Integrate persistent active job backend

### LINKED ISSUE #374: Rental#create is taking a long time
It seems like the problem is because of the views taking forever to render, i'd bet at least part of that is the mail, we are already delivering async with deliver_later but it seems like it still tries to render right away. I think the reason is explained here, https://stackoverflow.com/a/28780106/4463703

`Completed 200 OK in 30894ms (Views: 30733.9ms | ActiveRecord: 115.1ms)`

Sucker punch seems like it would work fine for our application and is self contained which makes things simple.  https://github.com/brandonhilkert/sucker_punch

Installing is easy too just add this to the config
`config.active_job.queue_adapter = :sucker_punch`

### PR DESCRIPTION
**Pull request by Cobchise**
### Closes #374 

Installed sidekiq gem. Works fine in development, will need extra work in production. Both sidekiq and redis need to be running alongside the app. There are a number of ways to achieve this including [the capistrano gem](https://github.com/seuros/capistrano-sidekiq) or making our own scripts on the production server. 

[Useful link](https://github.com/mperham/sidekiq/wiki/Deployment)

### CODE REVIEW

**Comment by anmerkl** [comment]
Is this good to go?
Did you finish the "extra work in production"

**Comment by Cobchise** [comment]
The code is good is to go, I'll set up the production side stuff and then ping here when that's complete

**Comment by Anbranin** [comment]
What kind of stuff needs to be done on the server? Please make sure you document what you did / are doing so more than one person knows how the server is configured. :)
Also, you may want to add the [capistrano sidekiq gem](https://github.com/seuros/capistrano-sidekiq) if you want capistrano to restart sidekiq.

**Comment by Cobchise** [comment]
https://blog.sensible.io/2013/08/20/setting-up-redis-for-production-environment.html

**Pull request merged**
