### PR TITLE
Added javascript for updating end time correctly on single day rental

### LINKED ISSUE #145: Error thrown when trying to create a 'single-day' rental any day other than today
When I try to create a 'single-day' rental on any day except the current day it throws an error. 

I believe this is because the rental is being created using a 'hidden-field' for the end date thats value is always the current date. So when the start date is changed to be after this set end date, the rental validations kick in and an error is thrown.

### PR DESCRIPTION
**Pull request by Cobchise**
### Fixes #145 ###

### CODE REVIEW

**Comment by phantompatrol** [comment]
RE: #146 , and this [comment](https://github.com/umts/probable-engine/pull/146#issuecomment-238839816), which one of these two solutions do we like best? @cmednieks @owlee @xliu3

**Comment by owlee** [comment]
I am going to say JS now client sided vs server sided change in case we have multiple client instances for the same time slot. I haven't found a clean solution (esp with modifying the datepicker() because bootstrap overrides my JS func).

**Comment by phantompatrol** [comment]
Having multiple clients is not an issue in either solution, as the reservation is being made as the rental saves.

I would just say to merge the one we like best, close the opposing one and cheer at merging your first PR

**Comment by owlee** [comment]
👍  Do I get merging powers from you or Metin? @phantompatrol

**Comment by phantompatrol** [comment]
@umayavuz !

**Comment by owlee** [comment]
Can't wait to merge my first PR at code review! 😰

**Pull request merged**
