### PR TITLE
Update seeds

### PR DESCRIPTION
**Pull request by phantompatrol**
This is a temporary measure as we rethink the connection with the Inventory. Not to be merged.

### CODE REVIEW

**Comment by phantompatrol** [comment]
@owlee , this is the update to the seeds that we discussed, but I would prefer not to merge this.

LONG story short, I think the inventory model could use some attention and this PR highlights it. Building out the issue here: https://github.com/umts/probable-engine/issues/75

**Comment by owlee** [comment]
screen shot 2016-06-23 at 9 16 26 am

Running seed file produce the error above. I have regenerated the api key and have recreated databases (dropped, created, and migrated) on both Probable and Aggressive. I will be looking more into it.

**Comment by phantompatrol** [comment]
@owlee , checking now

**Comment by phantompatrol** [comment]
Very odd. But for anyone listening in `db:drop/create/migrate/seed` on the local app and api rectified the issue.

**Comment by phantompatrol** [comment]
Closed, in favor of https://github.com/umts/probable-engine/pull/78

**Pull request closed without merging**
