### PR TITLE
Friendlier errors

### PR DESCRIPTION
**Pull request by cmednieks**
Fixing #164 , It gets rid of the unfriendly error page when there are no more carts available by redirecting back to the :new rental form. It does so by getting rid of the hooks in the model and calls `create_reservation` and `delete_reservation` explicitly in the rental controller.

### CODE REVIEW

**Comment by cmednieks** [comment]
Not sure why the merge did not go through correctly...

**Comment by tomecho** [comment]
@cmednieks if you're still available, did you mean to remove fee schedules from schema?

**Comment by cmednieks** [comment]
@tomecho oops, did not mean to do that

**Comment by tomecho** [comment]
#206 made some edits and put into

**Pull request closed without merging**
