### PR TITLE
Gemfile update and Rails update

### LINKED ISSUE #384: Upgrade Rails Version + update gems
I got a message "The nokogiri dependency defined in Gemfile.lock has a known critical severity security vulnerability in version range < 1.8.1 and should be updated." from Github, and then I looked in the Gemfile and realized we're a little bit out of date on everything.
We can update the Rails version to 5.1 and use the latest Nokogiri gem and everything should be great.

### PR DESCRIPTION
**Pull request by Cobchise**
### Closes #384 

Removed some version numbers from gemfile and ran bundle update. Also updated rails to 5.1.4

### CODE REVIEW

**Comment by Cobchise** [comment]
Needs a little more tweaking to fix depreciations and migration warnings

**Comment by anmerkl** [comment]
Is this good to go?

**Comment by Cobchise** [comment]
Not yet

**Comment by LiamBrandt** [comment]
Just ran `bundle update` and changed the version of parser that was yanked which was causing CI to fail (2.5.0.4): https://rubygems.org/gems/parser/versions

This is probably set to merge

**Pull request merged**
