### PR TITLE
Inventory api mocks

### LINKED ISSUE #30: inventory api mocks
Hey @jgthibodeau, @phantompatrol suggested we implement api fixtures so we are not dependent on aggressive-epsilon for testing.

### PR DESCRIPTION
**Pull request by tomecho**
fixes #30 
@dfaulken might want to look as these mocks to see if they conform to his api

### CODE REVIEW

**Comment by tomecho** [comment]
lots of code climate issues, should probably correct those

**Comment by tomecho** [comment]
oh woops
i accidently the pull request

**Comment by tomecho** [comment]
adding tests, but for now this should help with building the code that relies on this

**Comment by dfaulken** [comment]
Our README is current, so if this matches that, then it's fine. I'm not sure that an ActiveRecord model is necessarily the best way to go about mocking an API, but that's a decision for your team to make.

**Comment by tomecho** [comment]
@dfaulken being an active record was an accident (force of habit i suppose).  Its just a plain old model.  Is it to early to know the final resting point for the production api?

**Comment by dfaulken** [comment]
At this point it's only going to change if you all need it to.

**Pull request merged**
